### PR TITLE
Put docx info in the readme.md

### PR DESCRIPTION
**Pull request by jamesalbert**
Adhering to git standards is all. Plus I think it's easier for people who don't have word and don't want to open it in google docs.

### CODE REVIEW

**Comment by jamesalbert** [comment]
did you guys see my pr and add it in without merging it?

**Comment by jamesalbert** [comment]
noobs

**Comment by vincentqho** [comment]
No, I did not add in your pr without merging it. Some people are new to Github, others are not. Please keep things professional, and maybe one day you can...

Thank you for your pr.

**Comment by jamesalbert** [comment]
> Some people are new to Github, others are not. 

no worries, I was just poking fun at the person that did, calling them a noob.

> maybe one day you can...

maybe one day I can what?

you're welcome

**Pull request merged**
